[package]
name = "lingtree"
version = "1.0.0"
repository = "https://github.com/KenyC/typst-lingtree"
entrypoint = "lib.typ"
authors = ["Keny C <https://github.com/KenyC>"]
license = "MIT"
repository = "https://github.com/KenyC/typst-lingtree"
description = "Draws linguistic syntactic trees."
keywords = ["tree", "syntax", "linguistic tree", "syntactic tree"]
categories = ["visualization", "utility"]
disciplines = ["linguistics"]
exclude = ["manual.typ", "manual.pdf", "gallery/*", "Makefile"]

